[package]
name = "gridthorn_assets"
description = "Asset loading contracts for Gridthorn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
image.workspace = true
thiserror.workspace = true

[lints]
workspace = true
