[package]
name = "gridthorn_world"
description = "Provisional ECS world and schedule services for Gridthorn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bevy_ecs.workspace = true

[lints]
workspace = true
